export type JsonPrimitive = string | number | boolean | null;

export type JsonValue = JsonPrimitive | JsonObject | JsonValue[];

export interface JsonObject {
  [key: string]: JsonValue;
}

export const ERROR_CODES = {
  INVALID_ARGUMENT: "INVALID_ARGUMENT",
  AUTH_REQUIRED: "AUTH_REQUIRED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  REFRESH_INVALID: "REFRESH_INVALID",
  EMAIL_CODE_INVALID: "EMAIL_CODE_INVALID",
  EMAIL_CODE_EXPIRED: "EMAIL_CODE_EXPIRED",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  OAUTH_STATE_INVALID: "OAUTH_STATE_INVALID",
  FORBIDDEN: "FORBIDDEN",
  ADMIN_REQUIRED: "ADMIN_REQUIRED",
  USER_BANNED: "USER_BANNED",
  NOT_FOUND: "NOT_FOUND",
  QUESTION_NOT_ACCESSIBLE: "QUESTION_NOT_ACCESSIBLE",
  MISTAKE_NOT_FOUND: "MISTAKE_NOT_FOUND",
  CONFLICT: "CONFLICT",
  ATTEMPT_CONFLICT: "ATTEMPT_CONFLICT",
  UGC_ALREADY_REVIEWED: "UGC_ALREADY_REVIEWED",
  TARGET_PRIMARY_CONFLICT: "TARGET_PRIMARY_CONFLICT",
  CARD_NOT_DUE: "CARD_NOT_DUE",
  IMPORT_JOB_EXPIRED: "IMPORT_JOB_EXPIRED",
  LAST_ADMIN_PROTECTED: "LAST_ADMIN_PROTECTED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  PAGINATION_INVALID: "PAGINATION_INVALID",
  IMMUTABLE_FIELD: "IMMUTABLE_FIELD",
  PROVIDER_UNSUPPORTED: "PROVIDER_UNSUPPORTED",
  TARGET_LIMIT_EXCEEDED: "TARGET_LIMIT_EXCEEDED",
  ANSWER_INVALID: "ANSWER_INVALID",
  IMPORT_VALIDATION_FAILED: "IMPORT_VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  DAILY_LIMIT_EXCEEDED: "DAILY_LIMIT_EXCEEDED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  DEPENDENCY_UNAVAILABLE: "DEPENDENCY_UNAVAILABLE",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const ERROR_STATUS = {
  [ERROR_CODES.INVALID_ARGUMENT]: 400,
  [ERROR_CODES.AUTH_REQUIRED]: 401,
  [ERROR_CODES.TOKEN_EXPIRED]: 401,
  [ERROR_CODES.REFRESH_INVALID]: 401,
  [ERROR_CODES.EMAIL_CODE_INVALID]: 401,
  [ERROR_CODES.EMAIL_CODE_EXPIRED]: 401,
  [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: 401,
  [ERROR_CODES.OAUTH_STATE_INVALID]: 401,
  [ERROR_CODES.FORBIDDEN]: 403,
  [ERROR_CODES.ADMIN_REQUIRED]: 403,
  [ERROR_CODES.USER_BANNED]: 403,
  [ERROR_CODES.NOT_FOUND]: 404,
  [ERROR_CODES.QUESTION_NOT_ACCESSIBLE]: 404,
  [ERROR_CODES.MISTAKE_NOT_FOUND]: 404,
  [ERROR_CODES.CONFLICT]: 409,
  [ERROR_CODES.ATTEMPT_CONFLICT]: 409,
  [ERROR_CODES.UGC_ALREADY_REVIEWED]: 409,
  [ERROR_CODES.TARGET_PRIMARY_CONFLICT]: 409,
  [ERROR_CODES.CARD_NOT_DUE]: 409,
  [ERROR_CODES.IMPORT_JOB_EXPIRED]: 409,
  [ERROR_CODES.LAST_ADMIN_PROTECTED]: 409,
  [ERROR_CODES.VALIDATION_FAILED]: 422,
  [ERROR_CODES.PAGINATION_INVALID]: 422,
  [ERROR_CODES.IMMUTABLE_FIELD]: 422,
  [ERROR_CODES.PROVIDER_UNSUPPORTED]: 422,
  [ERROR_CODES.TARGET_LIMIT_EXCEEDED]: 422,
  [ERROR_CODES.ANSWER_INVALID]: 422,
  [ERROR_CODES.IMPORT_VALIDATION_FAILED]: 422,
  [ERROR_CODES.RATE_LIMITED]: 429,
  [ERROR_CODES.DAILY_LIMIT_EXCEEDED]: 429,
  [ERROR_CODES.INTERNAL_ERROR]: 500,
  [ERROR_CODES.DEPENDENCY_UNAVAILABLE]: 503,
} satisfies Record<ErrorCode, number>;

const ERROR_MESSAGES = {
  [ERROR_CODES.INVALID_ARGUMENT]: "请求格式不合法",
  [ERROR_CODES.AUTH_REQUIRED]: "请先登录",
  [ERROR_CODES.TOKEN_EXPIRED]: "登录状态已过期",
  [ERROR_CODES.REFRESH_INVALID]: "刷新凭证无效",
  [ERROR_CODES.EMAIL_CODE_INVALID]: "邮箱验证码无效",
  [ERROR_CODES.EMAIL_CODE_EXPIRED]: "邮箱验证码已过期",
  [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: "邮箱或密码错误",
  [ERROR_CODES.OAUTH_STATE_INVALID]: "授权状态无效或已过期",
  [ERROR_CODES.FORBIDDEN]: "没有执行该操作的权限",
  [ERROR_CODES.ADMIN_REQUIRED]: "需要管理员权限",
  [ERROR_CODES.USER_BANNED]: "账号已被封禁",
  [ERROR_CODES.NOT_FOUND]: "资源不存在",
  [ERROR_CODES.QUESTION_NOT_ACCESSIBLE]: "题目不存在或不可访问",
  [ERROR_CODES.MISTAKE_NOT_FOUND]: "错题不存在或不可访问",
  [ERROR_CODES.CONFLICT]: "资源状态冲突",
  [ERROR_CODES.ATTEMPT_CONFLICT]: "答题记录重复提交",
  [ERROR_CODES.UGC_ALREADY_REVIEWED]: "内容已被审核",
  [ERROR_CODES.TARGET_PRIMARY_CONFLICT]: "目标院校设置冲突",
  [ERROR_CODES.CARD_NOT_DUE]: "卡片尚未到复习时间",
  [ERROR_CODES.IMPORT_JOB_EXPIRED]: "导入任务已过期",
  [ERROR_CODES.LAST_ADMIN_PROTECTED]: "不能封禁最后一名有效管理员",
  [ERROR_CODES.VALIDATION_FAILED]: "请求参数不合法",
  [ERROR_CODES.PAGINATION_INVALID]: "分页参数不合法",
  [ERROR_CODES.IMMUTABLE_FIELD]: "请求包含不可修改字段",
  [ERROR_CODES.PROVIDER_UNSUPPORTED]: "不支持该登录方式",
  [ERROR_CODES.TARGET_LIMIT_EXCEEDED]: "目标院校数量超过限制",
  [ERROR_CODES.ANSWER_INVALID]: "答案格式或选项无效",
  [ERROR_CODES.IMPORT_VALIDATION_FAILED]: "导入文件校验失败",
  [ERROR_CODES.RATE_LIMITED]: "请求过于频繁，请稍后重试",
  [ERROR_CODES.DAILY_LIMIT_EXCEEDED]: "今日使用额度已用完",
  [ERROR_CODES.INTERNAL_ERROR]: "服务器内部错误",
  [ERROR_CODES.DEPENDENCY_UNAVAILABLE]: "服务暂时不可用",
} satisfies Record<ErrorCode, string>;

export interface AppErrorOptions {
  status?: number;
  message?: string;
  details?: JsonValue;
  cause?: unknown;
}

export class AppError extends Error {
  readonly status: number;

  readonly code: ErrorCode;

  readonly details: JsonValue | null;

  readonly internalCause?: unknown;

  constructor(code: ErrorCode, options: AppErrorOptions = {}) {
    super(options.message ?? ERROR_MESSAGES[code]);

    this.name = "AppError";
    this.status = options.status ?? ERROR_STATUS[code];
    this.code = code;
    this.details = options.details ?? null;
    this.internalCause = options.cause;
  }
}

export function isAppError(error: unknown): error is AppError {
  return error instanceof AppError;
}

export function toAppError(error: unknown): AppError {
  if (isAppError(error)) {
    return error;
  }

  return new AppError(ERROR_CODES.INTERNAL_ERROR, { cause: error });
}

export function getDefaultErrorMessage(code: ErrorCode): string {
  return ERROR_MESSAGES[code];
}
